### PR TITLE
Link Color constants to RGB function

### PR DESCRIPTION
**Pull request by italicize**
Also, link to a specific glossary entry.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md"></a>
### [VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md)
 - **Line 14**: **[Warning]** Illegal link: `[constants](vbe-glossary.md#constant)` -- missing bookmark. The file Language-Reference-VBA/articles/vbe-glossary.md doesn&#39;t contain a bookmark named constant.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808021856446782-636%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4Xv3bWz7%2FrXzxwJT%2FPZQ9kQ5aiNTAKVec%2FhsOPqbGDU%3D&st=2018-08-02T18%3A58%3A09Z&se=2018-09-02T19%3A03%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by italicize** [comment]
Should the table show decimal values instead of hexadecimal? Excel and Word use decimal values when they record a macro. In the VBE, ```Debug.Print vbCyan``` returns 16776960.

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md"></a>
### [VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md)
 - **Line 14**: **[Warning]** Illegal link: `[constants](vbe-glossary.md#constant)` -- missing bookmark. The file Language-Reference-VBA/articles/vbe-glossary.md doesn&#39;t contain a bookmark named constant.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808021856473082-636%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=76Lyz%2FtJcLdDalkQMqpSUoDVDD9tF%2FsCjzuhNteQ1rc%3D&st=2018-08-02T19%3A04%3A08Z&se=2018-09-02T19%3A09%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by italicize** [comment]
A link to a specific glossary entry is more helpful. Is the warning about illegal links accurate? The following link works, https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/vbe-glossary#constant

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md"></a>
### [VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md)
 - **Line 14**: **[Warning]** Illegal link: `[constants](vbe-glossary.md#constant)` -- missing bookmark. The file Language-Reference-VBA/articles/vbe-glossary.md doesn&#39;t contain a bookmark named constant.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808071822185705-636%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WI7RJhIVkrrLxiwMlUMZIOGttGM%2Buyab%2Bz4IOQzDGkQ%3D&st=2018-08-07T18%3A23%3A35Z&se=2018-09-07T18%3A28%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fcolor-constants.md"></a>
### [VBA/Language-Reference-VBA/articles/color-constants.md](https://github.com/italicize/VBA-content/blob/patch-46/VBA/Language-Reference-VBA/articles/color-constants.md)
 - **Line 14**: **[Warning]** Illegal link: `[constants](vbe-glossary.md#constant)` -- missing bookmark. The file Language-Reference-VBA/articles/vbe-glossary.md doesn&#39;t contain a bookmark named constant.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808071822285734-636%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TeCDPZ5S5Bj1ImFJ%2FhQVmFXaNemIWGrGiFzlYUm%2BTLk%3D&st=2018-08-07T18%3A30%3A12Z&se=2018-09-07T18%3A35%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
