### PR TITLE
Update workbook-exportasfixedformat-method-excel.md

### PR DESCRIPTION
**Pull request by IvenBach**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |-----|-----|-----|-----|. Line: 66, position: 9, file: vba/templates/methodTemplate.html Line 66, position 9.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |-----|. Line: 166, position: 9, file: vba/templates/objectTemplate.html Line 166, position 9.

<a name=""></a>
### []()
 - **[Error]** This error message is shown because some errors happened when normalize Content or TOC. Possible reasons. 1: Some documents after build are still malformed xml, can&#39;t be shown on OP website. Please ref the other errors to check your content to see if there&#39;s any invalid html tag. 2. Some toc files normalized failed. That may be because toc file contains invalid charactors, please ref the other toc normalized errors to fix. Otherwise, please open a ticket in http://SiteHelp.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804022339233744-501%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Rg9042Ds3UXBB%2FA39Frv3bzvF%2BvCmFAeWWwFr3hO8CM%3D&st=2018-04-02T23%3A42%3A21Z&se=2018-05-03T23%3A47%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |-----|-----|-----|-----|. Line: 66, position: 9, file: vba/templates/methodTemplate.html Line 66, position 9.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/IvenBach/VBA-content/blob/patch-1/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |-----|. Line: 166, position: 9, file: vba/templates/objectTemplate.html Line 166, position 9.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804022339333516-501%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AfhAdse40cWs4Lm8eiOP7sHZZnZeBdDcfBItq5%2BrhbU%3D&st=2018-04-02T23%3A50%3A23Z&se=2018-05-03T23%3A55%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/VBA-content, working directory: W:\eezn-s, target branch: master, target branch commit: a254c108173fe27f8568aa4cff6f0a9dad0dc922, source branch: bb679226ca5eadf2a49b26bb6c50ac08/patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804040057498659-501%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fgo90g1lGcnIEcWb%2FhVMMOay258ha4C6B7Tuc6SWXpg%3D&st=2018-04-04T00%3A55%3A38Z&se=2018-05-05T01%3A00%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/VBA-content, working directory: W:\jd2u-s, target branch: master, target branch commit: a254c108173fe27f8568aa4cff6f0a9dad0dc922, source branch: bb679226ca5eadf2a49b26bb6c50ac08/patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804040059386772-501%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BHpMTU14KMpX7NktoMNb6%2B3MDrOXWEdfTTe%2BCUdJqQA%3D&st=2018-04-04T00%3A58%3A15Z&se=2018-05-05T01%3A03%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
Templates throwing errors, I removed the blank lines. Please sign CLA, fix sytax issue, and reopen.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/VBA-content, working directory: W:\5mdr-s, target branch: master, target branch commit: a254c108173fe27f8568aa4cff6f0a9dad0dc922, source branch: bb679226ca5eadf2a49b26bb6c50ac08/patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804040059279638-501%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uC4HzsxAyq1FJ4ZTbJFU7ztO%2BCLwyI%2Br7BilzHJVbVg%3D&st=2018-04-04T01%3A00%3A52Z&se=2018-05-05T01%3A05%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
