### PR TITLE
Fix ampersand issue

### PR DESCRIPTION
**Pull request by Kagre**
I'm not the greatest with github, but I believe this fixes issue: https://github.com/OfficeDev/VBA-content/issues/588

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/accessobject-datecreated-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-datecreated-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-datemodified-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-datemodified-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/add-a-value-to-a-bound-combo-box.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/add-a-value-to-a-bound-combo-box.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/all-distinct-distinctrow-top-predicates-microsoft-access-sql.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/all-distinct-distinctrow-top-predicates-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allow-users-to-add-items-to-an-unbound-combo-box.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/allow-users-to-add-items-to-an-unbound-combo-box.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/and-operator.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/and-operator.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-accesserror-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-accesserror-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-brokenreference-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-brokenreference-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-build-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-build-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-buildcriteria-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-buildcriteria-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-closecurrentdatabase-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-closecurrentdatabase-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-codecontextobject-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-codecontextobject-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-currentuser-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-currentuser-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-davg-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-davg-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dbengine-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dbengine-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dcount-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dcount-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-deletecontrol-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-deletecontrol-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-deletereportcontrol-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-deletereportcontrol-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlast-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlast-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlookup-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlookup-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmax-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmax-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmin-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmin-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdev-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdev-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdevp-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdevp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvar-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-eval-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-eval-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-featureinstall-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-featureinstall-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-followhyperlink-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-followhyperlink-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-hyperlinkpart-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-hyperlinkpart-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-languagesettings-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-languagesettings-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-modules-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-modules-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-nz-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-nz-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-opencurrentdatabase-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-opencurrentdatabase-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-printer-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-printer-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-printers-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-printers-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-productcode-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-productcode-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-references-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-references-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-refreshtitlebar-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-refreshtitlebar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-run-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-run-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-setdefaultworkgroupfile-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-setdefaultworkgroupfile-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-usercontrol-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-usercontrol-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-vbe-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-vbe-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-version-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-version-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/apply-a-filter-when-opening-a-form-or-report.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/apply-a-filter-when-opening-a-form-or-report.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/assign-a-control-a-value-from-a-table.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/assign-a-control-a-value-from-a-table.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/attachment-properties-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/attachment-properties-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/axis-example-vbscript.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/axis-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-beforeupdate-event-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-columnhidden-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-columnhidden-property-access.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807170804523605-605%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=arr72QK9EkLpEapSszfMwA3YVA2NIe9DzFv44DCSfPk%3D&st=2018-07-17T08%3A08%3A37Z&se=2018-08-17T08%3A13%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/accessobject-datecreated-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-datecreated-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-datemodified-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-datemodified-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/add-a-value-to-a-bound-combo-box.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/add-a-value-to-a-bound-combo-box.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/all-distinct-distinctrow-top-predicates-microsoft-access-sql.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/all-distinct-distinctrow-top-predicates-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allow-users-to-add-items-to-an-unbound-combo-box.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/allow-users-to-add-items-to-an-unbound-combo-box.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/and-operator.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/and-operator.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-accesserror-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-accesserror-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-brokenreference-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-brokenreference-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-build-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-build-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-buildcriteria-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-buildcriteria-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-closecurrentdatabase-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-closecurrentdatabase-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-codecontextobject-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-codecontextobject-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-currentuser-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-currentuser-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-davg-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-davg-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dbengine-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dbengine-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dcount-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dcount-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-deletecontrol-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-deletecontrol-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-deletereportcontrol-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-deletereportcontrol-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlast-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlast-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlookup-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlookup-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmax-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmax-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmin-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmin-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdev-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdev-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdevp-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdevp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvar-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-eval-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-eval-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-featureinstall-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-featureinstall-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-followhyperlink-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-followhyperlink-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-hyperlinkpart-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-hyperlinkpart-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-languagesettings-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-languagesettings-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-modules-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-modules-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-nz-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-nz-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-opencurrentdatabase-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-opencurrentdatabase-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-printer-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-printer-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-printers-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-printers-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-productcode-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-productcode-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-references-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-references-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-refreshtitlebar-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-refreshtitlebar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-run-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-run-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-setdefaultworkgroupfile-method-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-setdefaultworkgroupfile-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-usercontrol-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-usercontrol-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-vbe-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-vbe-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-version-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/application-version-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/apply-a-filter-when-opening-a-form-or-report.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/apply-a-filter-when-opening-a-form-or-report.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/assign-a-control-a-value-from-a-table.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/assign-a-control-a-value-from-a-table.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/attachment-properties-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/attachment-properties-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/axis-example-vbscript.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/axis-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-beforeupdate-event-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-columnhidden-property-access.md](https://github.com/Kagre/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-columnhidden-property-access.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807170805022710-605%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xoGK42TdaGI0tsnDm6rqhLa%2FN0Hf5jrgR6SD1S83p1o%3D&st=2018-07-17T08%3A17%3A07Z&se=2018-08-17T08%3A22%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by italicize** [comment]
Bravo @Kagre for fixing a format problem in hundreds of files. Can you describe the steps you used? 
 
@Lauragra or @lindalu-MSFT please confirm that you can accept a pull request that fixes multiple files.

**Comment by lindalu-MSFT** [comment]
@Kagre This content is no longer being published. The new content is about to be merged to live on MicrosoftDocs/VBA-docs.

**Comment by lindalu-MSFT** [comment]
@italicize @Kagre This PR will not be merged. When the new VBA-docs is published on MicrosoftDocs (sometime today, we hope) then you'll have to reapply your fix. This repo was supposed to be blocked from making changes, I'm looking into what happened and why you were able to make changes.

**Comment by Kagre** [comment]
@italicize basically,

I updated my fork to the current master: [SO Article](https://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381).

[Installed Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)

downloaded the repository files locally: [GitHub Article](https://services.github.com/on-demand/github-cli/clone-repo-cli)

fiddled around with PowerShell a bit until I got it to do what I wanted https://github.com/OfficeDev/VBA-content/issues/588:
```powershell
$re = [regex]'(?s)```vb([^`]*&;)+[^`]*```'
filter fltr{
   $content=(gc $_) -join "`n"
   $mList = $re.matches($content)
   if($mList.count -gt 0){
#      write-host "********* $($_.fullname)"
      foreach($ToFind in $mList.value){
#         write-host "********* ToFind"
#         write-host $ToFind
         $ToSet = ($ToFind -replace '&;','&')
#         $ToSet = ($ToFind -replace '(?''head''\s+)&;(?''foot''\s+)','${head}&${foot}')
#         write-host "********* ToSet"
#         write-host $ToSet
         $content = $content.replace($ToFind,$ToSet)
      }
      $pth = resolve-path $_ -relative
#      $pth = ".\diff\$pth";$null = (ni $pth -type file -force)
      sc $pth $content -force
      resolve-path $pth -relative
   }
}
ls *.md -recurse | fltr | ac Updated.txt
```

Git commandline also installed Git GUI which was easier to use to push the updated files back to my fork, then I created a pull request from my fork to the master through the web interface.

(of course it wasn't quite this straight forward when I was working through it; I just had to try things, some worked, some didn't, but this is the gist of what got me there in the end.)

if you want to give it a go; there's some spacing issues I've noticed here and there but haven't had the time to dig into which you could try fixing as well.

@lindalu-MSFT I believe I should be ok to run it again, but is there a way for me to check when the new VBA-docs is published?

**Comment by italicize** [comment]
@Kagre It looks like the VBA reference has moved. 
- Old repository, https://github.com/OfficeDev/VBA-content
- New repository, https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/overview/index.md
 
Also, it looks like the formatting is worse now. 
- Old article, https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/select-case-statement.md
- New article, https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/select-case-statement.md
 
These fixes were needed even before the files moved:
- Add a space before links, if missing.
- Add a space between an italic mark (_) and a bold mark (*).
- Add a blank line between single-spaced lines.
- Change bold Syntax and Remarks to headings.
- Replace &; with & only.
 
@lindalu-MSFT Could Microsoft please fix the formatting problems? Each time the files moved, formatting problems showed up.

**Comment by italicize** [comment]
Also, @Kagre thanks for posting the steps. I think I had a conceptual block about the step where you created a pull request from your fork to the master. I had some feeling like Microsoft wouldn't let it work that way. But that's how GitHub works, so what was I worried about?

**Comment by Kagre** [comment]
@italicize lol, Microsoft recently bought GitHub, so who knows what the future may hold.

**Comment by Kagre** [comment]
@italicize now I'm curious, would you suggest **Syntax** and **Remarks** should be at the double level like **Example**, or all at the triple level? Also @lindalu-MSFT would that bold to header update break the MSDN conversion?

plus it looks like there is one more to add to your list, any link to the vbe-glossary.md should probably have the hash sub reference added too.

**Comment by Kagre** [comment]
digging through some of the other documentation looks like they should be at the double level

**Comment by italicize** [comment]
@Kagre You're right that the glossary links should go to specific terms. 
 
@lindalu-MSFT Why does a link like `[constants](vbe-glossary.md#constant)` receive an "illegal link" error? See https://github.com/OfficeDev/VBA-content/pull/636

**Comment by Linda-Editor** [comment]
Moved to https://github.com/MicrosoftDocs/VBA-Docs/pull/36 and completed there.

**Pull request closed without merging**
