### PR TITLE
Update application-pathseparator-property-excel.md

### PR DESCRIPTION
**Pull request by ashleedawg**
The "\" character was not showing since it needs to be entered in markup as "\\".
 Also removed unnecessary semicolon.  
My first OfficeDev edit.  :-)

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-pathseparator-property-excel.md](https://github.com/ashleedawg/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-pathseparator-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C25%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804250148107747-532%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xyUmV26GHNZ5%2F9zalVIq7ULqhhAR54%2BXOuSiA50xCs4%3D&st=2018-04-25T01%3A50%3A48Z&se=2018-05-26T01%3A55%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-pathseparator-property-excel.md](https://github.com/ashleedawg/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-pathseparator-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C25%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804250148212778-532%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0ifuDHRYxIerc2YuPwdZPpvoVH6GOphqGsqushZtj3M%3D&st=2018-04-25T01%3A58%3A52Z&se=2018-05-26T02%3A03%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ashleedawg** [comment]
So uhhh, am I missing a step to make the change go live?

**Comment by lindalu-MSFT** [comment]
@ashleedawg Awesome! Congrats & thanks so much! We really appreciate the help we get from the community.

**Comment by lindalu-MSFT** [comment]
@ashleedawg No, not missing a step. I review the PR's on Tuesdays and Thursdays around 3 PM. Or you can @ me or send me an email at lindalu@microsoft.com. Once I accepts your PR, it will go live. As in, should be live today shortly!

**Comment by ashleedawg** [comment]
Great, thanks!  I know the change is literally a single character, but it's the milestone. I didn't realize this documentation can be community edited, and I use it several times a day and have an eye for errors.


And you review is as a Microsoft employee?  (Sorry I haven't seen a thorough explanation of the process.)


________________________________

**Comment by lindalu-MSFT** [comment]
@ashleedawg Yes, I review all the pull requests and issues that come in from the community. So please, feel free to click "contribute" and fix, or add, any content that you think will help improve the documentation. I review on Tuesdays/Thursdays and push changes to the live server then. I am an editor in the Office Engineering org. This repo was orphaned for about a year, but I love VBA and volunteered to take it on! So I appreciate all the help I can get! Cheers, lindalu

**Pull request merged**
