### PR TITLE
Format the Dir function

### PR DESCRIPTION
**Pull request by italicize**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/dir-function.md](https://github.com/italicize/VBA-content/blob/patch-32/VBA/Language-Reference-VBA/articles/dir-function.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C27%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807272138133551-620%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Cal%2FR8g%2BdRN4cD%2BjNOaB2NR17bkCVKWUNzaqIczQG%2FA%3D&st=2018-07-27T21%3A42%3A19Z&se=2018-08-27T21%3A47%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/dir-function.md](https://github.com/italicize/VBA-content/blob/patch-32/VBA/Language-Reference-VBA/articles/dir-function.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C27%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807272138238192-620%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lpAZaw68VB7mtNqOGzlvqtIvap%2Fi8S2BJFpmcaq5W5Y%3D&st=2018-07-27T21%3A49%3A26Z&se=2018-08-27T21%3A54%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/dir-function.md](https://github.com/italicize/VBA-content/blob/patch-32/VBA/Language-Reference-VBA/articles/dir-function.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C9%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808092219067576-620%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=og2PxVMn0lAlFF1TQzUnL%2FJpS6nX57sua9OUG8QAIKQ%3D&st=2018-08-09T22%3A20%3A49Z&se=2018-09-09T22%3A25%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/dir-function.md](https://github.com/italicize/VBA-content/blob/patch-32/VBA/Language-Reference-VBA/articles/dir-function.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C9%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808092219169612-620%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cyriecXHxTW%2FsmeKGliXfZOAf8c4bOnvdyl6%2BWvZMNg%3D&st=2018-08-09T22%3A27%3A18Z&se=2018-09-09T22%3A32%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
