### PR TITLE
fixed minor formatting issues

### PR DESCRIPTION
**Pull request by LuckyMajky**
- links formatting <br/>
 - broken tables

### CODE REVIEW

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/VBA-content, working directory: W:\bcpi-s, target branch: master, target branch commit: 9ccc746a089168074147c715ee07138cd5328a32, source branch: ba41935b909f6af729256e7af6a465cd/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201802012050297082-467%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0dke00VhFA%2FLQlSlGt%2BJuMn5fzU6K2DoaYOsbXlBDUw%3D&st=2018-02-01T20%3A48%3A13Z&se=2018-03-04T20%3A53%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/VBA-content, working directory: W:\iiak-s, target branch: master, target branch commit: 9ccc746a089168074147c715ee07138cd5328a32, source branch: ba41935b909f6af729256e7af6a465cd/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201802012050433878-467%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pYwqGuQMjuKyVNQRQnH2GFEWO4mSoYwai5pRgBQroXU%3D&st=2018-02-01T20%3A50%3A30Z&se=2018-03-04T20%3A55%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@LuckyMajky Thanks for your contributions! I verified topics rendered and resolved the merge conflict. Changes will be live shorty.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/0-database-engine-driver.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/0-database-engine-driver.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/5-database-engine-driver-1-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-1-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/all-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/all-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allowbypasskey-property.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allowbypasskey-property.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/alltables-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/alltables-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/alter-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/alter-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/and-operator.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/and-operator.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/appicon-property.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/appicon-property.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-davg-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-davg-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dbengine-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dbengine-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dcount-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dcount-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-ddeexecute-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-ddeexecute-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dfirst-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dfirst-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlast-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlast-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlookup-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlookup-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmax-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmax-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmin-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmin-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdev-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdev-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdevp-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdevp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dsum-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dsum-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvar-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvarp-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvarp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-nz-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-nz-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-references-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-references-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/as-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/as-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/asc-desc-microsoft-access-sql-reserved-words.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/asc-desc-microsoft-access-sql-reserved-words.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/attachment-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/attachment-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/by-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/by-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/calculate-elapsed-time.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/calculate-elapsed-time.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/chart-control.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/chart-control.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-ado-wfc-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-ado-wfc-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-visual-c-plus-plus-syntax-index-with-import.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-visual-c-plus-plus-syntax-index-with-import.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-afterupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-afterupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/command-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/command-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/connection-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/connection-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/container-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/container-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/control-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/control-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/controls-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/controls-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/count-function-microsoft-access-sql.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/count-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/create-a-shortcut-menu-for-a-form-form-control-or-report.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/create-a-shortcut-menu-for-a-form-form-control-or-report.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/create-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/create-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/datafactory-object-query-method-and-createobject-method-example-vbscript.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/datafactory-object-query-method-and-createobject-method-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/dataspace-object-and-createobject-method-example-vbscript.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/dataspace-object-and-createobject-method-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/delete-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/delete-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/determine-whether-the-current-record-is-a-new-record-in-a-form.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/determine-whether-the-current-record-is-a-new-record-in-a-form.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C29%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803292221437670-467%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Mk82xB4T5xQi7y9tmD33ZYWN9VebHLz5NbLp0YbC3No%3D&st=2018-03-29T22%3A24%3A38Z&se=2018-04-29T22%3A29%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/0-database-engine-driver.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/0-database-engine-driver.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/5-database-engine-driver-1-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-1-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/all-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/all-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allowbypasskey-property.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allowbypasskey-property.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/alltables-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/alltables-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/alter-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/alter-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/and-operator.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/and-operator.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/appicon-property.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/appicon-property.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-davg-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-davg-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dbengine-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dbengine-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dcount-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dcount-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-ddeexecute-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-ddeexecute-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dfirst-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dfirst-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlast-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlast-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dlookup-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dlookup-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmax-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmax-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dmin-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dmin-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdev-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdev-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dstdevp-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dstdevp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dsum-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dsum-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvar-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvar-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-dvarp-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-dvarp-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-nz-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-nz-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/application-references-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/application-references-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/as-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/as-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/asc-desc-microsoft-access-sql-reserved-words.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/asc-desc-microsoft-access-sql-reserved-words.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/attachment-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/attachment-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/avg-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/boundobjectframe-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/boundobjectframe-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/by-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/by-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/calculate-elapsed-time.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/calculate-elapsed-time.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/chart-control.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/chart-control.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-ado-wfc-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-ado-wfc-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/collections-visual-c-plus-plus-syntax-index-with-import.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/collections-visual-c-plus-plus-syntax-index-with-import.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-afterupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-afterupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/command-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/command-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/connection-ado-for-visual-c-plus-plus-syntax.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/connection-ado-for-visual-c-plus-plus-syntax.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/container-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/container-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/control-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/control-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/controls-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/controls-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/count-function-microsoft-access-sql.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/count-function-microsoft-access-sql.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/create-a-shortcut-menu-for-a-form-form-control-or-report.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/create-a-shortcut-menu-for-a-form-form-control-or-report.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/create-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/create-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/datafactory-object-query-method-and-createobject-method-example-vbscript.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/datafactory-object-query-method-and-createobject-method-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/dataspace-object-and-createobject-method-example-vbscript.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/dataspace-object-and-createobject-method-example-vbscript.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/delete-microsoft-access-sql-reserved-word.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/delete-microsoft-access-sql-reserved-word.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/determine-whether-the-current-record-is-a-new-record-in-a-form.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/determine-whether-the-current-record-is-a-new-record-in-a-form.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C29%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803292221539946-467%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dANi07NxI1DtXy%2BDYuqGBKC%2FBamgft%2FMZihkJePUrDA%3D&st=2018-03-29T22%3A31%3A59Z&se=2018-04-29T22%3A36%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
