### PR TITLE
Update object-data-type.md

### PR DESCRIPTION
**Pull request by jacobmorehouse**
Made minor changes. Question on this one - is there a way to point those links to the actual anchors in the glossary, for example "#object-variable"? If there is an easy way for me to do that I can make those changes as I go as well.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/object-data-type.md](https://github.com/jacobmorehouse/VBA-content/blob/patch-8/VBA/Language-Reference-VBA/articles/object-data-type.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803222215124457-492%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nutf1NMJ%2FT6fJtm2KetLQydgiRGKgq6ocuqKhXsgedg%3D&st=2018-03-22T22%3A20%3A44Z&se=2018-04-22T22%3A25%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@jacobmorehouse Hi Jacob, yes, you can link to a section in markdown. You can link in the same article: [link text](#anchor) or you can link to a section in a different article: [link text](article-name.md#anchor). In  your case, I.e. [run-time](vbe-glossary.md#run-time). 

Note that the anchor is the section heading with spaces replaced with a hyphen. You might consider removing the hyphen from the link text:  [run time](vbe-glossary.md#run-time)

**Comment by lindalu-MSFT** [comment]
@jacobmorehouse ha! my markdown example rendered! 

Link to a section of an article <pre>[link text](#anchor)</pre>
Link to a section in a different article <pre>[link text](#article-name.md#anchor)</pre>

**Comment by jacobmorehouse** [comment]
Fantastic, thank you. I'll incorporate that into future edits, and may circle back to previous ones that I can make a bit more precise.

**Pull request merged**
