### PR TITLE
Format the Collection object

### PR DESCRIPTION
**Pull request by italicize**
Add links. Delete duplicate text.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/collection-object.md](https://github.com/italicize/VBA-content/blob/patch-65/VBA/Language-Reference-VBA/articles/collection-object.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808151848425450-662%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=antRHdw5P4703Lng23ocJhzx1nUjAQ%2FbyPA9IdsjFGg%3D&st=2018-08-15T19%3A10%3A41Z&se=2018-09-15T19%3A15%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/collection-object.md](https://github.com/italicize/VBA-content/blob/patch-65/VBA/Language-Reference-VBA/articles/collection-object.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808151848526274-662%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gdlaWjVj4jLDhVZBKSRKWf8Nitc7dT%2Fk6fJgnGTv8TQ%3D&st=2018-08-15T19%3A37%3A25Z&se=2018-09-15T19%3A42%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/collection-object.md](https://github.com/italicize/VBA-content/blob/patch-65/VBA/Language-Reference-VBA/articles/collection-object.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808152021581942-662%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bbj6%2FZ2lk0iEv8OZLPJjcf3cHJo3aKorLdEkEpkLwRU%3D&st=2018-08-15T20%3A43%3A41Z&se=2018-09-15T20%3A48%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/collection-object.md](https://github.com/italicize/VBA-content/blob/patch-65/VBA/Language-Reference-VBA/articles/collection-object.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808152022083019-662%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LZppR%2Bxmkln%2BSRtZMo3oCfrNuGxS4iCH1oPJnG22xYI%3D&st=2018-08-15T21%3A11%3A10Z&se=2018-09-15T21%3A16%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
