### PR TITLE
Adjusted a format and some descriptions.

### PR DESCRIPTION
**Pull request by GustavBrock**
Added "Localized" for weekday names and month names.
Removed "oooo" as this format(string) is unknown in VBA.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md](https://github.com/GustavBrock/VBA-content/blob/patch-2/VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807031317241919-589%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JKKt%2FxjE4QsVK6rc4cC905J64bAyfbvxOHk7IocT8GM%3D&st=2018-07-03T13%3A24%3A03Z&se=2018-08-03T13%3A29%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md](https://github.com/GustavBrock/VBA-content/blob/patch-2/VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807031317342562-589%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YiLxMnSqzkhJ9znoFkHNi6Si4c9%2FOxP7twyMAgF90kQ%3D&st=2018-07-03T13%3A36%3A20Z&se=2018-08-03T13%3A41%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md](https://github.com/GustavBrock/VBA-content/blob/patch-2/VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807051536328533-589%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4dSg09qhsaMVpuHCeTXTmLXZiJZUpi9lT60Ry0dxGsE%3D&st=2018-07-05T15%3A38%3A46Z&se=2018-08-05T15%3A43%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md](https://github.com/GustavBrock/VBA-content/blob/patch-2/VBA/Language-Reference-VBA/articles/format-function-visual-basic-for-applications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807051536430636-589%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AlAIl3CuGsJ%2B6PezY7tZNXQka3XrAw6XRfjc%2FZqb4qo%3D&st=2018-07-05T15%3A45%3A57Z&se=2018-08-05T15%3A50%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
