### PR TITLE
BugFix

### PR DESCRIPTION
**Pull request by LuckyMajky**
Found and fixed several issues:
 - broken link
 - typos
 - broken image

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-isloaded-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-isloaded-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-notinlist-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-notinlist-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-istrusted-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-istrusted-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-openform-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-openform-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-sendobject-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-transfertext-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-transfertext-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-beforeupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-openargs-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-openargs-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/image-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/image-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-nodata-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-nodata-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-open-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-open-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-page-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-page-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-recordsource-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-recordsource-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/section-paint-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/section-paint-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/subform-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/subform-object-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201711152216264461-424%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OdNSLMnn0g4FGHX6bPvkzjgtZqhd1eoflH%2F2OvmZyPk%3D&st=2017-11-15T22%3A49%3A30Z&se=2017-12-16T22%3A54%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-isloaded-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-isloaded-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-notinlist-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-notinlist-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-istrusted-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-istrusted-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-openform-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-openform-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-sendobject-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-transfertext-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-transfertext-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-beforeupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-openargs-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-openargs-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/image-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/image-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-nodata-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-nodata-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-open-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-open-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-page-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-page-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-recordsource-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-recordsource-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/section-paint-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/section-paint-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/subform-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/subform-object-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201711152216362265-424%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gdlVJFzpFZHcpPQSVoieQ75kgrR9fEFyR7C8TdKCXPQ%3D&st=2017-11-15T23%3A23%3A33Z&se=2017-12-16T23%3A28%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-isloaded-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-isloaded-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-notinlist-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-notinlist-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-istrusted-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-istrusted-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-sendobject-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-transfertext-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-transfertext-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-beforeupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-openargs-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-openargs-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/image-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/image-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-nodata-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-nodata-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-page-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-page-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-recordsource-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-recordsource-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/section-paint-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/section-paint-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/subform-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/subform-object-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C23%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201801230215334197-424%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ly3LMkL6aZYa3cMSRev%2BjdZPTv6jR4fqLeYpllB8q9Q%3D&st=2018-01-23T02%3A18%3A27Z&se=2018-02-23T02%3A23%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/5-database-engine-driver-2-of-2.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/accessobject-isloaded-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-isloaded-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/allforms-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-notinlist-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-notinlist-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/combobox-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/currentproject-istrusted-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-istrusted-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-sendobject-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/docmd-transfertext-method-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-transfertext-method-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-beforeupdate-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-beforeupdate-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/form-openargs-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/form-openargs-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/image-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/image-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-nodata-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-nodata-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-object-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-page-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-page-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/report-recordsource-property-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/report-recordsource-property-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/section-paint-event-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/section-paint-event-access.md) | :white_check_mark:Succeeded | |
[VBA/Access-VBA/articles/subform-object-access.md](https://github.com/LuckyMajky/VBA-content/blob/master/VBA/Access-VBA/articles/subform-object-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C23%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201801230215418430-424%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=v8LkUYrmLoA2dZSFxzsstgInWfP%2F79KOzLFVGdbutC4%3D&st=2018-01-23T02%3A26%3A45Z&se=2018-02-23T02%3A31%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
