### PR TITLE
Update d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.md

### PR DESCRIPTION
**Pull request by UrsRohner**
Solver Engine Codes :
1 = "GRG-Nichtlinear" => für kontinuierliche nichtlineare Probleme
2 = "Simplex LP" => für lineare Probleme
3 = "EA (Evolutionärer Algorithmus)" => für nicht kontinuierliche Probleme

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.md](https://github.com/UrsRohner/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201703301619133296-308%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.md](https://github.com/UrsRohner/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201703301619241711-308%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ms4999** [comment]
VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.patch

**Comment by ms4999** [comment]
VBA/Excel-VBA/articles/d24a6a7b-e4d9-e315-d0a6-8b7c80a38ede.patch

**Comment by lindalu-MSFT** [comment]
@UrsRohner Because this PR was overlooked for so long, this branch has merge conflicts. I am closing this PR, and if the problem still persists and needs to be corrected, please open a new PR.

**Pull request closed without merging**
