### PR TITLE
Range.Width returns a Double value in points

### PR DESCRIPTION
**Pull request by italicize**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-width-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-35/VBA/Excel-VBA/articles/range-width-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302028595708-623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BVMzoTX1OltFDH27vg7%2FJ9MULfWo6J3KiYCQF5rWiN8%3D&st=2018-07-30T20%3A31%3A55Z&se=2018-08-30T20%3A36%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-width-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-35/VBA/Excel-VBA/articles/range-width-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302029098109-623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WZ5H2PPt%2Frcf9ZJro0WwLd2SofzyM8wLvQ62je2cYPM%3D&st=2018-07-30T20%3A39%3A14Z&se=2018-08-30T20%3A44%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-width-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-35/VBA/Excel-VBA/articles/range-width-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C10%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808100000171891-623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=K%2FbtQ3fJt8aGAux63HVOTfyoujfiLA5HAwM9rdXf4DM%3D&st=2018-08-10T00%3A01%3A44Z&se=2018-09-10T00%3A06%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-width-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-35/VBA/Excel-VBA/articles/range-width-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C10%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808100000194092-623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=RrD9hHQMAhhde1yhZD5MwlQd9nu8QWSKbDPkZsPDWzA%3D&st=2018-08-10T00%3A08%3A04Z&se=2018-09-10T00%3A13%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository (as part of [pull request #61](https://github.com/MicrosoftDocs/VBA-Docs/pull/61)), so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
