### PR TITLE
The Range.RowHeight property sets multiple rows

### PR DESCRIPTION
**Pull request by italicize**
+ Changed "first row" to "rows" in the opening sentence after testing.
+ Changed the variable type because `? VarType(Selection.RowHeight) = vbDouble` returned True.
+ Added a remark about "all rows in a range."
+ Changed the note about merged cells to a note about rows of different heights.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807301855387806-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QFGy1ePtutDdQTBDh0ATIg6vEuFzRDvvDlYROP6PGto%3D&st=2018-07-30T18%3A57%3A55Z&se=2018-08-30T19%3A02%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807301855488943-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DpigdJUxfzDS3Ek33bEuw8ALk7nXHCQX73H%2FXtUMMlM%3D&st=2018-07-30T19%3A05%3A30Z&se=2018-08-30T19%3A10%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302050490013-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=N%2Fpj04HKmhfQZmi4gz0%2BQ%2BT%2BcvcJNdaMPaeglXauxmA%3D&st=2018-07-30T20%3A53%3A18Z&se=2018-08-30T20%3A58%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302050593174-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=p7TJzna5upop6etq%2FiZZIUQetrO96UcbMo3GQ9wdKss%3D&st=2018-07-30T21%3A01%3A02Z&se=2018-08-30T21%3A06%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C10%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808102319032314-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HAzIlDD7iPxX4GYiTMQ4W8ermJ%2Bi0xBG7pI%2Bha7d4Ik%3D&st=2018-08-10T23%3A20%3A40Z&se=2018-09-10T23%3A25%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-rowheight-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-33/VBA/Excel-VBA/articles/range-rowheight-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C10%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808102319129453-621%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O4o77FRZ2FYWwzRpsjN86K2T9omO7jboHNd%2FCcoNwYo%3D&st=2018-08-10T23%3A27%3A21Z&se=2018-09-10T23%3A32%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
