### PR TITLE
Format the LTrim, RTrim, and Trim functions

### PR DESCRIPTION
**Pull request by italicize**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808032136471016-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mrLsc0Y6FvUUrbUZJkFSjPICtfwjWP8rzMdCQVHFk4Y%3D&st=2018-08-03T21%3A55%3A07Z&se=2018-09-03T22%3A00%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808032136569749-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lY72WN4Wfp%2BF7zPJMiVjgT2uoDW6fYhGjWQ2amPJIb0%3D&st=2018-08-03T22%3A01%3A18Z&se=2018-09-03T22%3A06%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fltrim-rtrim-and-trim-functions.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fltrim-rtrim-and-trim-functions.md"></a>
### [VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md)
 - **Line 42**: **[Warning]** Invalid file link:(~/Language-Reference-VBA/articles/worksheetfunction-trim-method-excel.md).
 - **Line 53**: **[Warning]** Invalid file link:(~/Language-Reference-VBA/articles/worksheetfunction-object-excel.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061831372499-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Iamyyt8yQ67ezPr3%2FGFDUi0mdSsWO8%2BHoaP7jDGjIGM%3D&st=2018-08-06T18%3A32%3A55Z&se=2018-09-06T18%3A37%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :warning:Warning | | [Details](#user-content-VBA%2FLanguage-Reference-VBA%2Farticles%2Fltrim-rtrim-and-trim-functions.md)

<a name="VBA%2FLanguage-Reference-VBA%2Farticles%2Fltrim-rtrim-and-trim-functions.md"></a>
### [VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md)
 - **Line 42**: **[Warning]** Invalid file link:(~/Language-Reference-VBA/articles/worksheetfunction-trim-method-excel.md).
 - **Line 53**: **[Warning]** Invalid file link:(~/Language-Reference-VBA/articles/worksheetfunction-object-excel.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061831471235-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=E01QZuTeWdalA2XMFgB9xaYQiEylPlrKaPIqjPQbSbA%3D&st=2018-08-06T18%3A39%3A23Z&se=2018-09-06T18%3A44%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061842129428-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YlpUheZCQdo7XAZvjMd9dsMNWrmL%2FpzdgFnrJVAIf%2FQ%3D&st=2018-08-06T18%3A45%3A26Z&se=2018-09-06T18%3A50%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md](https://github.com/italicize/VBA-content/blob/patch-51/VBA/Language-Reference-VBA/articles/ltrim-rtrim-and-trim-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061842029227-642%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gXoNSWLz5PG83QItJrub%2FqYWCnfTM1YiOwfCHwW2eao%3D&st=2018-08-06T18%3A51%3A42Z&se=2018-09-06T18%3A56%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
