### PR TITLE
The Range.Height property returns a Double value

### PR DESCRIPTION
**Pull request by italicize**
+ `? VarType(Selection.Height) = vbDouble` returns True. 
+ The property doesn't set a value.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-height-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-34/VBA/Excel-VBA/articles/range-height-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807301907062401-622%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1ofeybXWvbTB4lLqs71IimD1GJE2T9EhJDNjK%2F44OMo%3D&st=2018-07-30T19%3A09%3A47Z&se=2018-08-30T19%3A14%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-height-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-34/VBA/Excel-VBA/articles/range-height-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302034304618-622%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=y74kQj9%2FB9rypa55BQJfRJ8bB18nsgQ9ghV4EHGKGgI%3D&st=2018-07-30T20%3A36%3A26Z&se=2018-08-30T20%3A41%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/range-height-property-excel.md](https://github.com/italicize/VBA-content/blob/patch-34/VBA/Excel-VBA/articles/range-height-property-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C30%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807302034407470-622%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wGvsyhRVIhye7nYSw5QpPpbaGa4%2F8Gy7OYsVUU%2Fs4LM%3D&st=2018-07-30T20%3A43%3A39Z&se=2018-08-30T20%3A48%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository (as part of [pull request #61](https://github.com/MicrosoftDocs/VBA-Docs/pull/61)), so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
