### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by t-miller**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710021616369370-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x3N2u0MIq4blyRdtSa9meSHki5ry4itvV2RIwrYq54Q%3D&st=2017-10-02T16%3A20%3A21Z&se=2017-10-03T16%3A30%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710021616478047-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=y86Pv%2FnqJF3YmJiS%2FXAvsSJJDlZxMHKB5MFFrYUe9CQ%3D&st=2017-10-02T16%3A28%3A43Z&se=2017-10-03T16%3A38%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710021851535329-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6sw0GoPSdsqz%2BhO27A9NOTfUnE4peEge2rFbKLN3eeA%3D&st=2017-10-02T18%3A55%3A03Z&se=2017-10-03T19%3A05%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710021853251250-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vrYw1MfF5blkmJL6137zS9FWSithsH0DLFAVBo4q8Dg%3D&st=2017-10-02T19%3A04%3A13Z&se=2017-10-03T19%3A14%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C2%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710021853155859-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BHhcNlHjF2QE1VZ9zdI8vPds1EVhq8R5zFV2zmG%2BOdM%3D&st=2017-10-02T19%3A15%3A17Z&se=2017-10-03T19%3A25%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C23%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201801230037060173-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8jFTCqn5dfSEWG6PiBARicOzodRNo03pbfsjqDAoBX0%3D&st=2018-01-23T00%3A39%3A45Z&se=2018-02-23T00%3A44%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/application-inputbox-method-excel.md](https://github.com/t-miller/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/application-inputbox-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C23%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201801230037148729-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TZRpibLmMKT0NZXb5O%2BBUExTVysC%2BaQ5JmNEAJ%2FxWmQ%3D&st=2018-01-23T00%3A48%3A12Z&se=2018-02-23T00%3A53%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
