### PR TITLE
Fixed small typos

### PR DESCRIPTION
**Pull request by vaughns**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/9c4f4ba7-dd4b-0bc2-65b7-16455014097f.md](https://github.com/vaughns/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/9c4f4ba7-dd4b-0bc2-65b7-16455014097f.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201703221926155198-304%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/9c4f4ba7-dd4b-0bc2-65b7-16455014097f.md](https://github.com/vaughns/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/9c4f4ba7-dd4b-0bc2-65b7-16455014097f.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201703221926254772-304%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JohnAustin-MSFT** [comment]
Added commit contents to local master branch

**Comment by SixSigmaGuy** [comment]
Thanks!

**Pull request closed without merging**
