### PR TITLE
Add a table of enumerations

### PR DESCRIPTION
**Pull request by italicize**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/enumerations-word.md](https://github.com/italicize/VBA-content/blob/patch-23/VBA/Word-VBA/articles/enumerations-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C24%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807242137159523-612%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cAvi8ZBRN62%2FU6i3jL%2BlnHVEcr4BcPmV1L3w3D6FVXc%3D&st=2018-07-24T21%3A40%3A13Z&se=2018-08-24T21%3A45%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/enumerations-word.md](https://github.com/italicize/VBA-content/blob/patch-23/VBA/Word-VBA/articles/enumerations-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C24%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807242137259914-612%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=u5L%2BAnknABjVKcTXWGk3o1Lx6gKVDxmv%2Fbrmt9xlWZw%3D&st=2018-07-24T21%3A47%3A38Z&se=2018-08-24T21%3A52%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/enumerations-word.md](https://github.com/italicize/VBA-content/blob/patch-23/VBA/Word-VBA/articles/enumerations-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807311848596176-612%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KSYyyadlheaMr0eWo0Vt388DPkOUGjcsSPAG0jAOpe8%3D&st=2018-07-31T18%3A51%3A05Z&se=2018-08-31T18%3A56%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/enumerations-word.md](https://github.com/italicize/VBA-content/blob/patch-23/VBA/Word-VBA/articles/enumerations-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807311849097965-612%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q%2FabIVsWpCdcrwNyMtZUp5V62xictCujERsftpfuf24%3D&st=2018-07-31T18%3A58%3A18Z&se=2018-08-31T19%3A03%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/enumerations-word.md](https://github.com/italicize/VBA-content/blob/patch-23/VBA/Word-VBA/articles/enumerations-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C31%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201807311907180365-612%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=98Cb%2B1p9Ae7NOXnH8%2BU8uTXlK9bwnz75eFFjDTlLiPM%3D&st=2018-07-31T19%3A09%3A42Z&se=2018-08-31T19%3A14%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
