### PR TITLE
Update opentextfile-method.md: reference ForWriting

### PR DESCRIPTION
**Pull request by dhgutteridge**
Add references to the ForWriting constant, which was missing for unknown reasons. The code sample at the bottom of the page lists ForWriting, but the summary and table did not. (First noted in issue #549.)

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/opentextfile-method.md](https://github.com/dhgutteridge/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/opentextfile-method.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C14%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201805142339529279-556%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e2UBbO9qgw6t%2FZEAvNFs9C13dW3fjseKmn6mKKu2B7E%3D&st=2018-05-14T23%3A46%3A02Z&se=2018-06-14T23%3A51%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/opentextfile-method.md](https://github.com/dhgutteridge/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/opentextfile-method.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C14%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201805142340041040-556%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Wi%2FNBLP7wMABkEu2wECniMDFDxTXvgB%2FEBMmtHFMCdM%3D&st=2018-05-14T23%3A54%3A29Z&se=2018-06-14T23%3A59%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/opentextfile-method.md](https://github.com/dhgutteridge/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/opentextfile-method.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C19%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201805190009536856-556%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mV2pe68v0TaZJ5YOngHluR8GCbL0g5KZ4VIrGO%2BJARY%3D&st=2018-05-19T00%3A14%3A15Z&se=2018-06-19T00%3A19%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@dhgutteridge Hi! Thanks very much for the fix! I will merge your PR soon. Right now, we are moving the docs to another repo and there's a content freeze until it's complete. lindalu@microsoft.com

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/opentextfile-method.md](https://github.com/dhgutteridge/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/opentextfile-method.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C24%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201805242246491954-556%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5saEg6J4VNVDQhTCD9RiuFPIgzFMW%2BF4RZ0dNGZHCd0%3D&st=2018-05-24T22%3A48%3A42Z&se=2018-06-24T22%3A53%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by dhgutteridge** [comment]
Hi @lindalu-MSFT,

No worries. I just noticed I'd missed a grammatical fix in my earlier change set (should be "any" not "either"), and there's also a duplicate sentence that resulted from your merge activity, so I've fixed those. Unfortunately, I hit "enter" too soon on my commit and didn't write as descriptive a commit message as I meant to, sorry about that.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Language-Reference-VBA/articles/opentextfile-method.md](https://github.com/dhgutteridge/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/opentextfile-method.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C24%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201805242246594519-556%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0skKA%2Ftn5FkBx9N1aeGnkwteM2R1tL79GuScCqDHv2o%3D&st=2018-05-24T22%3A55%3A46Z&se=2018-06-24T23%3A00%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Comment by dhgutteridge** [comment]
Hi Linda,

Somehow the current state of this document in the new MicrosoftDocs/VBA-Docs repo missed one of the fixes you'd merged in the old repo (https://github.com/OfficeDev/VBA-content/pull/548/commits), and there was another tidbit that didn't make the last round of merges in this repo, too. I've fixed them for the new repo and have submitted a pull request there (https://github.com/MicrosoftDocs/VBA-Docs/pull/91).

Regards,

Dave

**Pull request closed without merging**
