### PR TITLE
Update document-save-method-word.md

### PR DESCRIPTION
**Pull request by HenrikHoyer**
documented parameters

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/document-save-method-word.md](https://github.com/HenrikHoyer/VBA-content/blob/patch-1/VBA/Word-VBA/articles/document-save-method-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C9%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803091202439592-477%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iqUWLwYsNeJkaQQInYFg8VLrUyHJtP4r1hK7gXgFBpo%3D&st=2018-03-09T12%3A05%3A08Z&se=2018-04-09T12%3A10%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/document-save-method-word.md](https://github.com/HenrikHoyer/VBA-content/blob/patch-1/VBA/Word-VBA/articles/document-save-method-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C9%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803091202547817-477%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jX5Mvxi9QxmPZnIkIby3G7Erco%2Fk4Avm%2F2JKINcVkcA%3D&st=2018-03-09T12%3A12%3A38Z&se=2018-04-09T12%3A17%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@HenrikHoyer Thanks much!

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/document-save-method-word.md](https://github.com/HenrikHoyer/VBA-content/blob/patch-1/VBA/Word-VBA/articles/document-save-method-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C20%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803202203371030-477%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mY3Ki3NAOmI%2BrwGbwEqkH7yVi5sr8alm8f462hvjHt0%3D&st=2018-03-20T22%3A06%3A34Z&se=2018-04-20T22%3A11%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
