### PR TITLE
**AUTO GENERATED - Adding vb tagging

### PR DESCRIPTION
**Pull request by iambmelt**
Not entirely certain how to QA this pull request, but here's the output of my doc-lang detector. Discovered many unhighlighted files.

**update - Thinking about this further, @Lauragra let's chat about what you think might be the best course of action for this update. I know this change is prohibitively large to check by eye.

### CODE REVIEW

**Comment by laschultz** [comment]
Hi iambelt,
Thanks for your contribution. I'm wondering if the tag added to these topics should be "vba" instead of "vb", similar to pull request #168.

**Comment by iambmelt** [comment]
@laschultz I believe that to the end user there isn't a functional difference between designating Visual Basic vs. Visual Basic for Applications - I can make them all the same, but I think it should be lower priority: which would you prefer? Also, if you disagree, please let me know :smile:

**Comment by iambmelt** [comment]
Not to self: in future, adjust scoring to support sql/other lang mixture. Try to get that ready for Feb.

Thanks @Lauragra!

**Comment by iambmelt** [comment]
Make it a tool that can run on sample / doc checkins as a hook / quality check.

Thanks @Lauragra for the idea

/cc @davidchesnut

**Pull request merged**
