### PR TITLE
Updates to 3 Excel Calculation articles for Excel 2016

### PR DESCRIPTION
**Pull request by FastExcel**
Updatyed 3 articles 1 image and added 2 new images

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-improving-calcuation-performance.md)
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-performance-and-limit-improvements.md)
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-tips-for-optimizing-performance-obstructions.md)
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-improving-calcuation-performance.md"></a>
### [VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md)
 - **Line 31**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/5850692f-8a8c-43e8-944b-1a1b1e3056fe.md#xlAboutAuthor).

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-performance-and-limit-improvements.md"></a>
### [VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md)
 - **Line 135**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/28d47a27-06c3-4ac0-ae9b-18de73624669.md#Office2007excelPerf_BigGridIncreasedLimitsExcel).
 - **Line 164**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/28d47a27-06c3-4ac0-ae9b-18de73624669.md#MultithreadedCalculation).

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-tips-for-optimizing-performance-obstructions.md"></a>
### [VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md)
 - **Line 36**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlAboutAuthor).
 - **Line 264**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlSortedDataMissingValues).
 - **Line 1097**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlVBAUDF).
 - **Line 1189**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlMinUsedRange).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201709161445378439-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3inz52RYGRKnd2I14dBZKBATGR6tAk0jPQw2VPG1N38%3D&st=2017-09-16T14%3A48%3A22Z&se=2017-09-17T14%3A58%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-improving-calcuation-performance.md)
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-performance-and-limit-improvements.md)
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :warning:Warning | | [Details](#user-content-VBA%2FExcel-VBA%2Farticles%2Fexcel-tips-for-optimizing-performance-obstructions.md)
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-improving-calcuation-performance.md"></a>
### [VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md)
 - **Line 31**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/5850692f-8a8c-43e8-944b-1a1b1e3056fe.md#xlAboutAuthor).

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-performance-and-limit-improvements.md"></a>
### [VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md)
 - **Line 135**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/28d47a27-06c3-4ac0-ae9b-18de73624669.md#Office2007excelPerf_BigGridIncreasedLimitsExcel).
 - **Line 164**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/28d47a27-06c3-4ac0-ae9b-18de73624669.md#MultithreadedCalculation).

<a name="VBA%2FExcel-VBA%2Farticles%2Fexcel-tips-for-optimizing-performance-obstructions.md"></a>
### [VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md)
 - **Line 36**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlAboutAuthor).
 - **Line 264**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlSortedDataMissingValues).
 - **Line 1097**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlVBAUDF).
 - **Line 1189**: **[Warning]** Invalid file link:(~/Excel-VBA/articles/4fa7b661-b205-4df1-bd6e-a7c9f26c4fd1.md#xlMinUsedRange).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201709161445483070-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=M2qs1qWJygmPIT6grn3HRXpUb1XDAENSn8Oathg2wik%3D&st=2017-09-16T14%3A56%3A39Z&se=2017-09-17T15%3A06%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201709161514339461-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SZ%2Fn9fubRjRT4prj1GMUsWdpuYTI0SbNRNX9Arh7JYg%3D&st=2017-09-16T15%3A16%3A38Z&se=2017-09-17T15%3A26%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201709161514441336-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WwCdVm%2FFzNmo7ioon9LwXErYlob45%2FVwCKBDisxKjPw%3D&st=2017-09-16T15%3A23%3A48Z&se=2017-09-17T15%3A33%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710051853527745-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EsfxqgMfmuyGuslCFN6RWdqC%2FjOydsqQI6lH32v4DhY%3D&st=2017-10-05T18%3A59%3A51Z&se=2017-10-06T19%3A09%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710051854040202-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lI2AxICTrD2D3dFa1wUDj4s%2FIlDWAX0KcTc%2FLNSHKFg%3D&st=2017-10-05T19%3A09%3A53Z&se=2017-10-06T19%3A19%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710061106594164-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AWadBnNMGvOsgjS4ct0pXUgoH%2Bg%2BZSL6FPu27cLI0cg%3D&st=2017-10-06T11%3A11%3A13Z&se=2017-10-07T11%3A21%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710061107086424-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9YdGBdua3nZW0HiqFdn9QAa%2BENL%2FY3ebRKyZQuzJ6Vw%3D&st=2017-10-06T11%3A19%3A42Z&se=2017-10-07T11%3A29%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-improving-calcuation-performance.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-performance-and-limit-improvements.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ImprovingCalculationPerf_ForceFull.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.jpg) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/MVP_avatar.png](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/MVP_avatar.png) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg](https://github.com/FastExcel/VBA-content/blob/ExcelPerformance/VBA/Excel-VBA/articles/images/ocd_xl2010_ta_improvingcalculationperf_fig01.jpg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201710131954208837-388%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NV3A0ZL%2BwlUtPYoFZTY2IetRffqPX7d%2FVznVm8Fb1kY%3D&st=2017-10-13T19%3A58%3A17Z&se=2017-11-13T20%3A03%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
Looks fantastic! Thank you Charles!

**Comment by FastExcel** [comment]
Great – thanks for your help.

**Pull request merged**
