### PR TITLE
Update application-wordbasic-property-word.md

### PR DESCRIPTION
**Pull request by Vitosh**
Remove the dots between `Word.Basic` as far as the name of the object in VBA is without dots.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/application-wordbasic-property-word.md](https://github.com/Vitosh/VBA-content/blob/patch-2/VBA/Word-VBA/articles/application-wordbasic-property-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804031002000195-506%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kmlJDW53xGvWSK66HK97G2BtoV8P%2F1mB9N%2FIH4GGx2Q%3D&st=2018-04-03T10%3A05%3A06Z&se=2018-05-04T10%3A10%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/application-wordbasic-property-word.md](https://github.com/Vitosh/VBA-content/blob/patch-2/VBA/Word-VBA/articles/application-wordbasic-property-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804031002103017-506%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZMh%2BRIg5otG3AwJgcxxww8%2FO5Vy3f%2FKuKkbDSKbbr4E%3D&st=2018-04-03T10%3A12%3A35Z&se=2018-05-04T10%3A17%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804031240458740-506%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q3mM0JvFuPOwm2v3D%2BirXBnSxh5h%2BPEpmRFq1iVsBq8%3D&st=2018-04-03T12%3A38%3A47Z&se=2018-05-04T12%3A43%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Word-VBA/articles/application-wordbasic-property-word.md](https://github.com/Vitosh/VBA-content/blob/patch-2/VBA/Word-VBA/articles/application-wordbasic-property-word.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201804031240563172-506%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fguvwZRhC2EwqEIaayzM2kyTklonhdCzxoxI2Eqnxlk%3D&st=2018-04-03T12%3A47%3A08Z&se=2018-05-04T12%3A52%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@Vitosh THanks! I didn't know WordBasic was still around!

**Pull request merged**
