### PR TITLE
Change description of default value

### PR DESCRIPTION
**Pull request by LoonSongSoftware**
(At least in Access 2010) the "Locked" property for form controls means that the control is locked if the property is set to True and unlocked if False. Unless there is some subtlety in the language that I'm missing, all descriptions of "Locked" are reversed. Only when Locked is False can a user edit, add or delete data.

If you agree, the corresponding property descriptions in all other controls needs to be changed.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/textbox-locked-property-access.md](https://github.com/LoonSongSoftware/VBA-content/blob/patch-1/VBA/Access-VBA/articles/textbox-locked-property-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803031831166410-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SCKep8u2WX2hC0W4SVGR2jalV9YKZZOXKjc42mV99Rk%3D&st=2018-03-03T18%3A34%3A17Z&se=2018-04-03T18%3A39%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Access-VBA/articles/textbox-locked-property-access.md](https://github.com/LoonSongSoftware/VBA-content/blob/patch-1/VBA/Access-VBA/articles/textbox-locked-property-access.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C3%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803031831268113-475%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=J%2BSu%2FugMYbA4FmDmca58k%2B1CqKrW8jn9LC%2Btt71Dfrc%3D&st=2018-03-03T18%3A42%3A43Z&se=2018-04-03T18%3A47%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@LoonSongSoftware Thank you for the catch! You are correct. I verified that Locked = FALSE is the default for all controls except unbound object frames. The control functions normally and allows editing, adding, and deleting data.

**Comment by LoonSongSoftware** [comment]
So...at some point someone should do a global search through the repository for other controls (ComboBox, Label, etc.) and make the same change. The error is pervasive.

**Pull request merged**
