### PR TITLE
Update excel-tips-for-optimizing-performance-obstructions.md to include new VLOOKUP perf. improvements caveat

### PR DESCRIPTION
**Pull request by PrashSMSFT**
Add the caveat for VLOOKUP

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md](https://github.com/OfficeDev/VBA-content/blob/prashsmsftVLOOKUP/VBA/Excel-VBA/articles/excel-tips-for-optimizing-performance-obstructions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803221903362803-487%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mn5Cv6VPGZPtYa%2BpY7ATcMLKt5a%2FLOGWS7k0XrCOgKo%3D&st=2018-03-22T19%3A46%3A41Z&se=2018-04-22T19%3A51%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@davidchesnut This is tagged "wait for David." Is this related to the other PR 495 you submitted? Is it safe to merge this one?

**Comment by lindalu-MSFT** [comment]
Moved to April fork.

**Comment by Kagre** [comment]
For what it's worth, while you're at it you could also mention that instead of using a whole column/row reference in your cell formulas, using just the range which contains data will also speed it up. eg A1:A6500 instead of A:A, because there are a whole lot of "blank" cells that get looked at each time...

**Pull request closed without merging**
