### PR TITLE
Delete restriction on number of ConditionalFormats

### PR DESCRIPTION
**Pull request by derHoepp**
The restriction on three conditional formats for a range does no longer apply. Time to change the Documentation. (You cannot define more than three conditional formats for a range.)

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/formatconditions-add-method-excel.md](https://github.com/derHoepp/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/formatconditions-add-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201802220819046582-471%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pV%2F4tO32vBkuqXeQHw%2FuGe4LDNUSSvvp2Ynq229k5OI%3D&st=2018-02-22T08%3A21%3A48Z&se=2018-03-25T08%3A26%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/formatconditions-add-method-excel.md](https://github.com/derHoepp/VBA-content/blob/patch-1/VBA/Excel-VBA/articles/formatconditions-add-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C22%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201802220819154468-471%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UpP2fsubiGX%2FsKaPCqr58tq5f5tpEtMvyP3lWX7kPJs%3D&st=2018-02-22T08%3A29%3A03Z&se=2018-03-25T08%3A34%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@derHoepp Thanks for the suggestion! @JohnAustin-MSFT do you have a moment to confirm this and update the documentation, or advise me what needs to change so I can update? THANKS, LL

**Comment by lindalu-MSFT** [comment]
@JohnAustin-MSFT Actually, if you could just confirm his change is true, then I will accept and merge this PR. THANKS

**Pull request merged**
