### PR TITLE
Johnau templates

### PR DESCRIPTION
**Pull request by JohnAustin-MSFT**
Created template folder and three templates.

### CODE REVIEW

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |:-----|:-----|:-----|:-----|. Line: 61, position: 10, file: vba/templates/methodTemplate.html Line 61, position 10.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |:-----|. Line: 161, position: 10, file: vba/templates/objectTemplate.html Line 161, position 10.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803161818229342-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kIdM3jQXLQcVXl1i1yxGgz8TupDxvHhpO3I3mzh2ylo%3D&st=2018-03-16T18%3A21%3A26Z&se=2018-04-16T18%3A26%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |:-----|:-----|:-----|:-----|. Line: 61, position: 10, file: vba/templates/methodTemplate.html Line 61, position 10.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |:-----|. Line: 161, position: 10, file: vba/templates/objectTemplate.html Line 161, position 10.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C16%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803161818333977-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L7lZ3sF1o0tilUJyoeTsqaNtK1DAFT1gugT50L%2F5UAc%3D&st=2018-03-16T18%3A29%3A20Z&se=2018-04-16T18%3A34%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@JohnAustin-MSFT Thanks for the templates, these will be very helpful. Cheers, lindalu

**Comment by lindalu-MSFT** [comment]
@JohnAustin-MSFT I did not delete the branch **johnau-templates**, but you may do so any time.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |-----|-----|-----|-----|. Line: 66, position: 9, file: vba/templates/methodTemplate.html Line 66, position 9.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |:-----|. Line: 161, position: 10, file: vba/templates/objectTemplate.html Line 161, position 10.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C29%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803292225497994-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tJDnyDNJ6w3DNVMeY9MiwjKtvDdFYQ337MMh0QkvV%2BI%3D&st=2018-03-29T22%3A28%3A42Z&se=2018-04-29T22%3A33%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |-----|-----|-----|-----|. Line: 66, position: 9, file: vba/templates/methodTemplate.html Line 66, position 9.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |-----|. Line: 166, position: 9, file: vba/templates/objectTemplate.html Line 166, position 9.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C29%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803292226012367-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0ZG2NuFwiquZratvSGB3tJy33XMpHhBaJ%2BX%2BM5vQgzk%3D&st=2018-03-29T22%3A36%3A16Z&se=2018-04-29T22%3A41%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FmethodTemplate.md)
[VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md) | :x:Error | | [Details](#user-content-VBA%2Ftemplates%2FobjectTemplate.md)

<a name="VBA%2Ftemplates%2FmethodTemplate.md"></a>
### [VBA/templates/methodTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/methodTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/methodTemplate.md failed. Error: Invalid content: |-----|-----|-----|-----|. Line: 66, position: 9, file: vba/templates/methodTemplate.html Line 66, position 9.

<a name="VBA%2Ftemplates%2FobjectTemplate.md"></a>
### [VBA/templates/objectTemplate.md](https://github.com/OfficeDev/VBA-content/blob/johnau-templates/VBA/templates/objectTemplate.md)
 - **[Error]** Normalize file reference for file VBA/templates/objectTemplate.md failed. Error: Invalid content: |-----|. Line: 166, position: 9, file: vba/templates/objectTemplate.html Line 166, position 9.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C29%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201803292226352261-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lOQcmOsd1%2F%2FIhEMndtrE8LaqZYUb6FJURIhiOQJy048%3D&st=2018-03-29T22%3A43%3A27Z&se=2018-04-29T22%3A48%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
