### PR TITLE
Replace an unnecessary link to the object model

### PR DESCRIPTION
**Pull request by italicize**

### CODE REVIEW

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/worksheetfunction-object-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-object-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061834249920-645%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mvsxtV3xqrCMWo4U6mtdVhVcq3CPBatfeEuGNohURo4%3D&st=2018-08-06T18%3A35%3A33Z&se=2018-09-06T18%3A40%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/worksheetfunction-object-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-object-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061834350766-645%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zax3omgg5LTy83vC0X8r9vy2AeLJYwycAJ38QcMl1cc%3D&st=2018-08-06T18%3A41%3A31Z&se=2018-09-06T18%3A46%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/worksheetfunction-object-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-object-excel.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/worksheetfunction-trim-method-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-trim-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061858111063-645%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9KaRKGju8zBu31C8YzALK1YB4UnDIulAGid5nSZXxfo%3D&st=2018-08-06T18%3A59%3A12Z&se=2018-09-06T19%3A04%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[VBA/Excel-VBA/articles/worksheetfunction-object-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-object-excel.md) | :white_check_mark:Succeeded | |
[VBA/Excel-VBA/articles/worksheetfunction-trim-method-excel.md](https://github.com/italicize/VBA-content/blob/patch-53/VBA/Excel-VBA/articles/worksheetfunction-trim-method-excel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C6%5Cf8b5b3f0-7390-2e9e-6625-a74fa1ae6f0a%5CPullRequest%5C201808061858212928-645%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BHq344zn6O6CQSFwYEnM%2BlemhCnr4Dj9%2BG8rJ%2Fxk5ac%3D&st=2018-08-06T19%3A05%3A20Z&se=2018-09-06T19%3A10%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
All content in this repository has been migrated to a new repository (https://github.com/MicrosoftDocs/VBA-Docs). The changes in this PR have been applied in the new repository, so this PR is being closed. The changes will be published to the [live docs]( https://docs.microsoft.com/en-us/office/vba/api/overview) soon. Thank you for your contribution!

**Pull request closed without merging**
